language: java

notifications:
  email:
    on_success: never
    on_failure: always
    
matrix:
  include:
  - os: linux
    dist: trusty
    jdk: oraclejdk11
install: true

# -B enables non interactive mode and disables colors
# -v Display version information WITHOUT stopping build
script: mvn clean install -B -V -DRUNS_ON_CI=true

# See that the script is not run in isolation, because it changes global env variables.
after_success:
    - . ./.ci/after_success.sh
    
cache:
  directories:
  - $HOME/.m2
